version: '2.1'
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - api:api
      - app:app
  db:
    image: postgres:9.4.5
    env_file:
      - ./api/.env
    volumes:
      - /var/lib/postgresql/9.5/main:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "psql -h localhost -p 5432 -U postgres -v ON_ERROR_STOP=1 -c 'select version()' &> /dev/null"]
        test: ["CMD-SHELL", "pg_isready -U postgres"] #Are you really up?
        interval: 2s
        timeout: 30s
        retries: 15
  api:
    volumes:
      - ./api:/var/www/pomodoro
    build:
      context: ./api
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=http://dev.pomodoro.works
      - ENTRYPOINT=app
    tty: true
    stdin_open: true
  app:
    volumes:
      - ./app:/var/www/pomodoro
    build:
      context: ./app
    depends_on:
      - api
    environment:
      - REACT_APP_API_ENDPOINT=http://dev-api.pomodoro.works
      - ENTRYPOINT=development
    tty: true
    stdin_open: true
