version: '2.1'
services:
  db:
    image: postgres:9.4.5
    env_file:
      - /home/sizief/pomodoro_project/env.db
      # Check api/.env.db to see what should be inside this file
    volumes:
      - /var/lib/postgresql/9.5/main:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "psql -h localhost -p 5432 -U postgres -v ON_ERROR_STOP=1 -c 'select version()' &> /dev/null"]
        test: ["CMD-SHELL", "pg_isready -U postgres"] #Are you really up?
        interval: 2s
        timeout: 30s
        retries: 15
  api:
    build:
      context: ./api
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true
    ports:
     - 4000:4000
    env_file:
      - ./api/.env.prod
      - /home/sizief/pomodoro_project/env.db
  app:
    tty: true
    ports:
      - "4001:80"
    build:
      context: ./app
      dockerfile: Dockerfile_production
      args:
        -  GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - REACT_APP_GOOGLE_CLIENT_ID=547377203778-rnas01ng8irns54hpho81roosuoagucq.apps.googleusercontent.com
    tty: true
    stdin_open: true
