version: 2
jobs:
   #build:`dd
   #  #...
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "09:d3:82:cf:52:e0:cb:8a:50:ff:30:34:4e:a3:42:c2"
      - run:
          name: Deploy Over SSH
          command: |
             ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "echo 'logged in' && cd /var/www/pomodoro/ && git pull && GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID docker-compose -f docker-compose-prod.yml up --build"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      #- build
      - deploy:
          filters:
            branches:
              only: master # only deploy on the master branch
