FROM node:13.14.0-slim as build-deps
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN node config/last_commit_updater.js
RUN echo $REACT_APP_GOOGLE_CLIENT_ID
RUN yarn build

FROM nginx:alpine
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
