source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'rack'
gem 'puma'
gem 'dotenv'
gem 'faraday'
gem "sinatra-activerecord"
gem 'pg', '~> 0.18.4'
gem "rake"

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
end
