# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv'
gem 'faraday'
gem 'pg', '~> 0.18.4'
gem "puma", ">= 4.3.1"
gem 'rack'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'

group :test do
  gem 'factory_bot' 
  gem 'rack-test'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
  gem 'database_cleaner'
end
