# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv'
gem "faraday"
gem 'pg', '~> 0.18.4'
gem 'puma', '>= 4.3.3'
gem 'rack'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'

group :development do
  gem 'pry', '~> 0.13.1'
  gem 'pry-byebug'
  gem 'sinatra-reloader'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'rack-test'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
end
