# frozen_string_literal: true

require 'sinatra/activerecord/rake'

namespace :db do
  task :load_config do
    require './app'
  end
end

begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec)
  task test: :spec
rescue LoadError
  # no rspec available
end
